root = "."
tmp_dir = "tmp"

[build]
  cmd = "sh -c 'go build -o ./tmp/server ./cmd/api 2>&1 | tee ./tmp/build-errors.log'"
  entrypoint = "./tmp/server"
  delay = 1000
  exclude_dir = ["vendor", "tmp", "db/migrations", "content", "node_modules"]
  include_ext = ["go"]
  exclude_regex = ["_test\\.go$"]
  log = "build-errors.log"
  kill_delay = "0s"
  rerun = false

[log]
  time = true
  main_only = false

[color]
  main     = "magenta"
  watcher  = "cyan"
  build    = "yellow"
  runner   = "green"

[screen]
  clear_on_rebuild = true
  keep_scroll      = true
